# Generated by Django 3.2.4 on 2021-08-28 12:30

import cla_association.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'association")),
                ('slug', models.SlugField(verbose_name="Identifiant unique de l'association")),
                ('type', models.CharField(choices=[('club', 'Club de CLA'), ('commission', 'Commission de CLA'), ('bdx', 'BDX'), ('asso_1901', 'Association loi 1901')], max_length=250, verbose_name='Forme juridique')),
                ('category', models.CharField(choices=[('audiovisual', 'Audiovisuel'), ('sport', 'Autour du sport'), ('bdx', 'BDX'), ('bdx_list', 'BDX (Liste)'), ('foreign_cuture', 'Culture étrangère'), ('writing_drawing', 'Écriture et dessin'), ('open_minded', "Esprit d'ouverture"), ('events', 'Évènements'), ('gastronomy', 'Gastronomie'), ('enterprises', "Monde de l'entreprise"), ('engineering', "Monde de l'ingénieur"), ('music', 'Musique'), ('solidarity', 'Solidarité'), ('theater_cinema', 'Théâtre et cinéma'), ('residence_life', 'Vie sur la résidence'), ('other', 'Autre')], max_length=250, verbose_name='Catégorie')),
                ('description', models.TextField(max_length=255, verbose_name='Description rapide')),
                ('presentation_html', django_summernote.fields.SummernoteTextField(verbose_name="Présentation de l'association")),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=0, size=[500, 500], upload_to=cla_association.models.FilePath.association_logo, verbose_name="Logo de l'association")),
                ('display', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('active', models.BooleanField(default=True, help_text='Une association active peut effectuer des demandes de réservation du foyer, du synthé, du barbecue...', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AssociationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_role', models.CharField(choices=[('010_president', 'Président'), ('020_general_secretary', 'Secrétaire général'), ('030_treasurer', 'Trésorier'), ('040_secretary', 'Secrétaire'), ('050_vice_president', 'Vice président'), ('051_vice_president_i', 'VPI'), ('052_vice_president_e', 'VPE'), ('100_respo_event', 'Responsable événement'), ('999_custom', 'Personnalisé')], max_length=250, verbose_name='Poste')),
                ('_role_custom', models.CharField(blank=True, help_text='A indiquer avec le poste "Personnalisé"', max_length=250, null=True, verbose_name='Poste personnalisé')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cla_association.association')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='association_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ('_role', '_role_custom'),
            },
        ),
        migrations.CreateModel(
            name='AssociationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('000_website', 'Site web'), ('010_facebook', 'Facebook'), ('020_twitter', 'Twitter'), ('030_instagram', 'Instagram'), ('040_tiktok', 'Tiktok'), ('999_custom', 'Personnalisé')], max_length=250, verbose_name='Poste')),
                ('_type_custom', models.CharField(blank=True, help_text='A indiquer avec le type "Personnalisé"', max_length=250, null=True, verbose_name='Type personnalisé')),
                ('href', models.URLField(verbose_name='Lien')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cla_association.association')),
            ],
            options={
                'verbose_name': 'Liens',
                'verbose_name_plural': 'Liens',
                'ordering': ('_type', '_type_custom'),
            },
        ),
    ]
