# Generated by Django 3.2.4 on 2021-08-28 12:36

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cla_association', '0002_alter_association_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='presentation_html',
            field=django_summernote.fields.SummernoteTextField(blank=True, verbose_name="Présentation de l'association"),
        ),
    ]
