# Generated by Django 3.2.4 on 2021-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_association', '0003_alter_association_presentation_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sous-titre'),
        ),
    ]
