# Generated by Django 3.2.4 on 2021-08-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_association', '0004_association_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationlink',
            name='_type',
            field=models.CharField(choices=[('000_website', 'Site web'), ('010_facebook', 'Facebook'), ('020_twitter', 'Twitter'), ('030_instagram', 'Instagram'), ('040_tiktok', 'Tiktok'), ('050_twitch', 'Twitch'), ('999_custom', 'Personnalisé')], max_length=250, verbose_name='Poste'),
        ),
    ]
