# Generated by Django 3.2.4 on 2022-01-20 23:49

import cla_association.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cla_association', '0006_alter_associationlink__type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposed_on', models.DateField(default=datetime.date, help_text="Doit correspondre à l'année de fin du mandat", verbose_name='Date de dépot')),
                ('president', models.CharField(blank=True, max_length=75, verbose_name='Président')),
                ('treasurer', models.CharField(blank=True, max_length=75, verbose_name='Trésorier')),
                ('quitus', models.FileField(blank=True, help_text='De préférence au format PDF', null=True, upload_to=cla_association.models.FilePath.association_quitus, verbose_name='Quitus moral')),
                ('archive', models.FileField(blank=True, help_text="De préférence au format ZIP et contenant toutes les ressources intéressantes de l'association (logo, trésorerie, photos, ...)", null=True, upload_to=cla_association.models.FilePath.association_archive, verbose_name='Archive')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_folders', to='cla_association.association')),
            ],
            options={
                'verbose_name': 'Dossier de passation',
                'verbose_name_plural': 'Dossiers de passation',
                'ordering': ('-deposed_on', 'association__name'),
            },
        ),
    ]
