# Generated by Django 3.2.4 on 2022-01-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_association', '0007_handoverfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverfolder',
            name='opened',
            field=models.BooleanField(default=False, verbose_name="Les responsables de l'association peuvent déposer le quitus et l'archive"),
        ),
    ]
