# Generated by Django 3.2.4 on 2022-01-21 00:14

import cla_association.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_association', '0008_handoverfolder_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverfolder',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Le dossier est validé'),
        ),
        migrations.AlterField(
            model_name='handoverfolder',
            name='quitus',
            field=models.FileField(blank=True, help_text='De préférence au format PDF', null=True, upload_to=cla_association.models.FilePath.association_quitus, verbose_name='Quitus'),
        ),
    ]
