# Generated by Django 3.2.4 on 2022-01-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_association', '0011_alter_handoverfolder_deposed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverfolder',
            name='president',
            field=models.CharField(blank=True, max_length=75, verbose_name='Président sortant'),
        ),
        migrations.AlterField(
            model_name='handoverfolder',
            name='treasurer',
            field=models.CharField(blank=True, max_length=75, verbose_name='Trésorier sortant'),
        ),
    ]
