# Generated by Django 3.2.4 on 2021-08-23 20:29

import cla_registration.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_year', models.PositiveIntegerField(verbose_name='Année de la rentrée scolaire')),
                ('date_start', models.DateField(verbose_name="Date d'ouverture des inscriptions")),
                ('date_end', models.DateField(verbose_name='Date de fermeture des inscriptions')),
                ('ticketing_href_centrale_pack', models.URLField(blank=True, default=cla_registration.models.RegistrationSession.DefaultTicketingHref.ticketing_href_centrale_pack, null=True, verbose_name='Billetterie "[Centrale Lille] Pack Alumni+CLA"')),
                ('ticketing_href_centrale_cla', models.URLField(blank=True, default=cla_registration.models.RegistrationSession.DefaultTicketingHref.ticketing_href_centrale_cla, null=True, verbose_name='Billetterie "[Centrale Lille] Adhésion CLA"')),
                ('ticketing_href_centrale_dd_pack', models.URLField(blank=True, default=cla_registration.models.RegistrationSession.DefaultTicketingHref.ticketing_href_centrale_dd_pack, null=True, verbose_name='Billetterie "[Centrale Lille][Double diplôme] Pack Alumni+CLA"')),
                ('ticketing_href_centrale_dd_cla', models.URLField(blank=True, default=cla_registration.models.RegistrationSession.DefaultTicketingHref.ticketing_href_centrale_dd_cla, null=True, verbose_name='Billetterie "[Centrale Lille][Double diplôme] Adhésion CLA"')),
                ('ticketing_href_iteem_pack', models.URLField(blank=True, default=cla_registration.models.RegistrationSession.DefaultTicketingHref.ticketing_href_iteem_pack, null=True, verbose_name='Billetterie "[ITEEM] Pack Alumni+CLA"')),
                ('ticketing_href_iteem_cla', models.URLField(blank=True, default=cla_registration.models.RegistrationSession.DefaultTicketingHref.ticketing_href_iteem_cla, null=True, verbose_name='Billetterie "[ITEEM] Adhésion CLA"')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_registration', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'inscription")),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse mail personnel')),
                ('email_school', models.EmailField(max_length=254, verbose_name='Adresse mail scolaire')),
                ('phone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('birthdate', models.DateField(verbose_name='Date de naissance')),
                ('school', models.TextField(choices=[('centrale.centralelille.fr', 'École Centrale de Lille'), ('iteem.centralelille.fr', 'ITEEM'), ('enscl.centralelille.fr', 'ENSCL')], max_length=255, verbose_name='Ecole')),
                ('contribution', models.PositiveIntegerField(verbose_name='Montant de cotisation à régler')),
                ('pack', models.BooleanField(verbose_name="L'étudiant a choisi de cotiser avec le pack")),
                ('rgpd_agreement', models.BooleanField(verbose_name="L'étudiant a accepté que ses informations soient stockées et utilisées par Centrale Lille Associations")),
                ('rgpd_sharing_alumni', models.BooleanField(verbose_name="L'étudiant a accepté que ses informations soient partagées avec Centrale Lille Alumni")),
                ('account', models.OneToOneField(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='cla_registration.registrationsession')),
            ],
        ),
    ]
