# Generated by Django 3.2.4 on 2021-08-23 21:10

import cla_web.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationsession',
            options={'verbose_name': "Session d'inscriptions", 'verbose_name_plural': "Sessions d'inscriptions"},
        ),
        migrations.AlterField(
            model_name='registrationsession',
            name='school_year',
            field=models.PositiveIntegerField(default=cla_web.utils.next_back_to_school_year, verbose_name='Année de la rentrée scolaire'),
        ),
    ]
