# Generated by Django 3.2.4 on 2021-08-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_registration', '0003_auto_20210824_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': "Formulaire d'adhésion", 'verbose_name_plural': "Formulaires d'adhésion"},
        ),
        migrations.AlterModelOptions(
            name='registrationsession',
            options={'ordering': ('-date_start',), 'verbose_name': "Session d'adhésion", 'verbose_name_plural': "Sessions d'adhésion"},
        ),
        migrations.AddField(
            model_name='registration',
            name='original_school',
            field=models.CharField(max_length=255, null=True, verbose_name="École/université d'origine"),
        ),
    ]
