# Generated by Django 3.2.4 on 2021-08-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_registration', '0006_datasharinglogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationsession',
            options={'ordering': ('-date_start',), 'verbose_name': "Campagne d'adhésion", 'verbose_name_plural': "Campagnes d'adhésion"},
        ),
    ]
