# Generated by Django 3.2.4 on 2021-08-29 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cla_registration', '0007_alter_registrationsession_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRightAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=250, verbose_name='Nom')),
                ('birthdate', models.DateField(verbose_name='Date de naissance')),
                ('email_school', models.EmailField(max_length=254, verbose_name='Adresse mail école')),
                ('file', models.FileField(upload_to='', verbose_name="Formulaire de droit à l'image et à l'information")),
            ],
        ),
    ]
