# Generated by Django 3.2.4 on 2021-08-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_registration', '0009_auto_20210829_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagerightagreement',
            options={'ordering': ('-created_on',), 'verbose_name': "Formulaire de droit à l'image", 'verbose_name_plural': "Formulaires de droit à l'image"},
        ),
    ]
