# Generated by Django 3.2.4 on 2022-09-04 20:58

import cla_registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_registration', '0011_alter_registration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsession',
            name='ticketing_href_enscl_cla',
            field=models.URLField(blank=True, default=cla_registration.models.RegistrationSession.DefaultTicketingHref.ticketing_href_enscl_cla, null=True, verbose_name='Billetterie "[ENSCL] Adhésion CLA"'),
        ),
    ]
