# Generated by Django 3.2.4 on 2022-09-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_registration', '0012_registrationsession_ticketing_href_enscl_cla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_school',
            field=models.EmailField(help_text="Vérifier bien qu'elle correspond à celle indiquée sur la papier donné à l'étudiant par l'administration.<br><b>En cas d'erreur l'étudiant ne pourra pas accéder à son compte.</b>", max_length=254, verbose_name='Adresse mail scolaire'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='original_school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="École/université d'origine"),
        ),
    ]
