# Generated by Django 3.2.4 on 2025-08-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_registration', '0013_auto_20220910_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[('centrale_pack', '[Centrale Lille] Pack Alumni+CLA'), ('centrale_cla', '[Centrale Lille] Adhésion CLA'), ('centrale_dd_pack', '[Centrale Lille][Double diplôme] Pack Alumni+CLA'), ('centrale_dd_cla', '[Centrale Lille][Double diplôme] Adhésion CLA'), ('centrale_dd_inter_pack', '[Centrale Lille][Double diplôme International] Pack Alumni+CLA'), ('centrale_dd_inter_cla', '[Centrale Lille][Double diplôme International] Adhésion CLA'), ('iteem_pack', '[ITEEM] Pack Alumni+CLA'), ('iteem_cla', '[ITEEM] Adhésion CLA'), ('enscl_cla', '[ENSCL] Ahésion CLA')], max_length=255, null=True, verbose_name="Type d'adhésion"),
        ),
    ]
