# Generated by Django 3.2.4 on 2022-01-20 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbecuerules',
            options={'ordering': ('-created_on',), 'verbose_name': '[BARBECUE] Charte du barbecue', 'verbose_name_plural': '[BARBECUE] Chartes du barbecue'},
        ),
    ]
