# Generated by Django 3.2.4 on 2022-01-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_reservation', '0002_alter_barbecuerules_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationfoyer',
            name='beer_selection',
            field=models.TextField(blank=True, help_text='Indiquez sur chaque ligne "Bière : Nombre de fûts"', max_length=500, verbose_name='Sélection des fûts'),
        ),
    ]
