# Generated by Django 3.2.4 on 2022-01-21 20:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cla_reservation', '0004_auto_20220121_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSlotBarbecue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='RÉSERVÉ', max_length=50, verbose_name='Nom')),
                ('start_date', models.DateField(help_text='Sert aussi pour définir le début de la récurrence', verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('recurring', models.BooleanField(default=False, verbose_name='Événement récurent')),
                ('recurring_days', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (0, 'Dimanche')], max_length=13, verbose_name="Jour où à lieu l'événement")),
                ('end_recurring', models.DateField(blank=True, null=True, verbose_name='Date de fin de la récurrence')),
                ('starts_on', models.DateTimeField(editable=False)),
                ('ends_on', models.DateTimeField(editable=False)),
                ('admin_display', models.BooleanField(default=False, verbose_name="L'événement apparait sur le planning de l'administration")),
                ('member_display', models.BooleanField(default=True, verbose_name="L'événement apparait sur le planning des cotisants")),
            ],
            options={
                'verbose_name': '[BARBECUE] Créneau bloqué',
                'verbose_name_plural': '[BARBECUE] Créneaux bloqués',
            },
        ),
        migrations.CreateModel(
            name='BlockedSlotFoyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='RÉSERVÉ', max_length=50, verbose_name='Nom')),
                ('start_date', models.DateField(help_text='Sert aussi pour définir le début de la récurrence', verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('recurring', models.BooleanField(default=False, verbose_name='Événement récurent')),
                ('recurring_days', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (0, 'Dimanche')], max_length=13, verbose_name="Jour où à lieu l'événement")),
                ('end_recurring', models.DateField(blank=True, null=True, verbose_name='Date de fin de la récurrence')),
                ('starts_on', models.DateTimeField(editable=False)),
                ('ends_on', models.DateTimeField(editable=False)),
                ('admin_display', models.BooleanField(default=False, verbose_name="L'événement apparait sur le planning de l'administration")),
                ('member_display', models.BooleanField(default=True, verbose_name="L'événement apparait sur le planning des cotisants")),
            ],
            options={
                'verbose_name': '[FOYER] Créneau bloqué',
                'verbose_name_plural': '[FOYER] Créneaux bloqués',
            },
        ),
        migrations.CreateModel(
            name='BlockedSlotSynthe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='RÉSERVÉ', max_length=50, verbose_name='Nom')),
                ('start_date', models.DateField(help_text='Sert aussi pour définir le début de la récurrence', verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('recurring', models.BooleanField(default=False, verbose_name='Événement récurent')),
                ('recurring_days', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (0, 'Dimanche')], max_length=13, verbose_name="Jour où à lieu l'événement")),
                ('end_recurring', models.DateField(blank=True, null=True, verbose_name='Date de fin de la récurrence')),
                ('starts_on', models.DateTimeField(editable=False)),
                ('ends_on', models.DateTimeField(editable=False)),
                ('admin_display', models.BooleanField(default=False, verbose_name="L'événement apparait sur le planning de l'administration")),
                ('member_display', models.BooleanField(default=True, verbose_name="L'événement apparait sur le planning des cotisants")),
            ],
            options={
                'verbose_name': '[SYNTHE] Créneau bloqué',
                'verbose_name_plural': '[SYNTHE] Créneaux bloqués',
            },
        ),
    ]
