# Generated by Django 3.2.4 on 2022-01-21 22:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cla_reservation', '0005_blockedslotbarbecue_blockedslotfoyer_blockedslotsynthe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedslotbarbecue',
            name='admin_display',
            field=models.BooleanField(default=False, verbose_name="Ce créneau apparait sur le planning de l'administration"),
        ),
        migrations.AlterField(
            model_name='blockedslotbarbecue',
            name='member_display',
            field=models.BooleanField(default=True, verbose_name='Ce créneau apparait sur le planning des cotisants'),
        ),
        migrations.AlterField(
            model_name='blockedslotbarbecue',
            name='recurring_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (0, 'Dimanche')], max_length=13, verbose_name='Jour(s) où ont lieu ce créneau selon la récurrence'),
        ),
        migrations.AlterField(
            model_name='blockedslotfoyer',
            name='admin_display',
            field=models.BooleanField(default=False, verbose_name="Ce créneau apparait sur le planning de l'administration"),
        ),
        migrations.AlterField(
            model_name='blockedslotfoyer',
            name='member_display',
            field=models.BooleanField(default=True, verbose_name='Ce créneau apparait sur le planning des cotisants'),
        ),
        migrations.AlterField(
            model_name='blockedslotfoyer',
            name='recurring_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (0, 'Dimanche')], max_length=13, verbose_name='Jour(s) où ont lieu ce créneau selon la récurrence'),
        ),
        migrations.AlterField(
            model_name='blockedslotsynthe',
            name='admin_display',
            field=models.BooleanField(default=False, verbose_name="Ce créneau apparait sur le planning de l'administration"),
        ),
        migrations.AlterField(
            model_name='blockedslotsynthe',
            name='member_display',
            field=models.BooleanField(default=True, verbose_name='Ce créneau apparait sur le planning des cotisants'),
        ),
        migrations.AlterField(
            model_name='blockedslotsynthe',
            name='recurring_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (0, 'Dimanche')], max_length=13, verbose_name='Jour(s) où ont lieu ce créneau selon la récurrence'),
        ),
    ]
