# Generated by Django 3.2 on 2021-05-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancingparty',
            name='slug',
            field=models.SlugField(default='', max_length=150, unique=True, verbose_name="Identifiant unique de l'événement"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', max_length=150, unique=True, verbose_name="Identifiant unique de l'événement"),
            preserve_default=False,
        ),
    ]
