# Generated by Django 3.2 on 2021-06-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0002_auto_20210531_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistrationtype',
            options={'verbose_name': 'Type de place', 'verbose_name_plural': 'Types de place'},
        ),
    ]
