# Generated by Django 3.2 on 2021-06-01 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cla_ticketing', '0003_alter_eventregistrationtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancingparty',
            name='managers',
            field=models.ManyToManyField(related_name='_cla_ticketing_dancingparty_managers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='managers',
            field=models.ManyToManyField(related_name='_cla_ticketing_event_managers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
