# Generated by Django 3.2 on 2021-06-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0006_auto_20210601_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dancingpartyregistration',
            options={'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
    ]
