# Generated by Django 3.2 on 2021-06-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0007_auto_20210601_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistrationtype',
            name='open_to',
            field=models.CharField(choices=[('contributors', 'Cotisants'), ('non_contributors', 'Non cotisants'), ('both', 'Cotisants et non cotisants')], default='both', max_length=75, verbose_name='Ouvert aux'),
        ),
    ]
