# Generated by Django 3.2 on 2021-06-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0009_auto_20210604_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancingpartyregistration',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='A payer'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='A payer'),
        ),
    ]
