# Generated by Django 3.2 on 2021-06-05 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cla_ticketing', '0011_auto_20210605_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancingpartyregistration',
            name='student_status',
            field=models.CharField(choices=[('contributor', 'Cotisant'), ('non_contributor', 'Non cotisant')], editable=False, max_length=20, verbose_name="Statut de l'étudiant"),
        ),
        migrations.AlterField(
            model_name='dancingpartyregistration',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Laisser vide si l'inscrit n'est pas un cotisant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='student_status',
            field=models.CharField(choices=[('contributor', 'Cotisant'), ('non_contributor', 'Non cotisant')], editable=False, max_length=20, verbose_name="Statut de l'étudiant"),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Laisser vide si l'inscrit n'est pas un cotisant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
