# Generated by Django 3.2 on 2021-06-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0012_auto_20210605_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('event_manager', "Accès à l'interface de gestion des événements pour lesquels l'utilisateur est administrateur"),), 'verbose_name': "Billetterie d'événement", 'verbose_name_plural': "Billetteries d'événement"},
        ),
    ]
