# Generated by Django 3.2.4 on 2021-06-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0014_alter_eventregistrationtype_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancingparty',
            name='ticketing_href',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticketing_href',
        ),
        migrations.AddField(
            model_name='dancingparty',
            name='contributor_ticketing_href',
            field=models.URLField(blank=True, help_text='Laisser vide si aucune', null=True, verbose_name="Lien vers la billeterie d'encaissement pour les cotisants"),
        ),
        migrations.AddField(
            model_name='dancingparty',
            name='non_contributor_ticketing_href',
            field=models.URLField(blank=True, help_text='Laisser vide si aucune', null=True, verbose_name="Lien vers la billeterie d'encaissement pour les non cotisants"),
        ),
        migrations.AddField(
            model_name='event',
            name='contributor_ticketing_href',
            field=models.URLField(blank=True, help_text='Laisser vide si aucune', null=True, verbose_name="Lien vers la billeterie d'encaissement pour les cotisants"),
        ),
        migrations.AddField(
            model_name='event',
            name='non_contributor_ticketing_href',
            field=models.URLField(blank=True, help_text='Laisser vide si aucune', null=True, verbose_name="Lien vers la billeterie d'encaissement pour les non cotisants"),
        ),
        migrations.AddField(
            model_name='eventregistrationtype',
            name='admin_only',
            field=models.BooleanField(blank=True, default=False, verbose_name='Limité aux administrateurs'),
        ),
    ]
