# Generated by Django 3.2.4 on 2021-06-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0015_auto_20210607_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistrationtype',
            name='admin_only',
        ),
        migrations.AddField(
            model_name='eventregistrationtype',
            name='visible',
            field=models.BooleanField(blank=True, default=True, verbose_name='Accessible'),
        ),
    ]
