# Generated by Django 3.2.4 on 2021-06-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0016_auto_20210607_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancingpartyregistration',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
