# Generated by Django 3.2.4 on 2021-08-25 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cla_ticketing', '0018_auto_20210825_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancingpartyregistration',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dancingpartyregistration',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le'),
        ),
        migrations.AlterField(
            model_name='dancingpartyregistration',
            name='guarantor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Garant'),
        ),
        migrations.AlterField(
            model_name='dancingpartyregistration',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='A payé'),
        ),
        migrations.AlterField(
            model_name='dancingpartyregistration',
            name='staff_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='dancingpartyregistration',
            name='type',
            field=models.CharField(choices=[('hard', 'Avec alcool'), ('soft', 'Sans alcool')], default='hard', max_length=255, null=True, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='A payé'),
        ),
    ]
