# Generated by Django 3.2.4 on 2021-08-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0019_auto_20210825_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancingpartyregistration',
            name='type',
            field=models.CharField(choices=[('hard', 'Avec alcool'), ('soft', 'Sans alcool')], default=None, max_length=255, null=True, verbose_name='Place'),
        ),
    ]
