# Generated by Django 3.2.4 on 2021-08-25 19:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cla_ticketing', '0020_auto_20210825_2101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dancingpartyregistration',
            unique_together={('user', 'dancing_party')},
        ),
    ]
