# Generated by Django 3.2.4 on 2021-08-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0023_auto_20210826_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancingpartyregistrationcustomfield',
            name='admin_only',
            field=models.BooleanField(blank=True, default=False, verbose_name='Disponible seulement du côté administrateur'),
        ),
        migrations.AlterField(
            model_name='dancingpartyregistrationcustomfield',
            name='required',
            field=models.BooleanField(blank=True, default=False, verbose_name='Requis'),
        ),
        migrations.AlterField(
            model_name='eventregistrationcustomfield',
            name='admin_only',
            field=models.BooleanField(blank=True, default=False, verbose_name='Disponible seulement du côté administrateur'),
        ),
        migrations.AlterField(
            model_name='eventregistrationcustomfield',
            name='required',
            field=models.BooleanField(blank=True, default=False, verbose_name='Requis'),
        ),
    ]
