# Generated by Django 3.2.4 on 2021-08-26 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0024_auto_20210826_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistrationCustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text_value', models.CharField(max_length=255, null=True)),
                ('boolean_value', models.BooleanField(null=True)),
                ('file_value', models.FileField(upload_to='registration_custom_field_file')),
                ('field', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cla_ticketing.eventregistrationcustomfield')),
                ('registration', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='cla_ticketing.eventregistration')),
            ],
            options={
                'verbose_name': 'Champ additionnel',
                'verbose_name_plural': 'Champs additionnels',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DancingPartyRegistrationCustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text_value', models.CharField(max_length=255, null=True)),
                ('boolean_value', models.BooleanField(null=True)),
                ('file_value', models.FileField(upload_to='registration_custom_field_file')),
                ('field', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cla_ticketing.dancingpartyregistrationcustomfield')),
                ('registration', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='cla_ticketing.dancingpartyregistration')),
            ],
            options={
                'verbose_name': 'Champ additionnel',
                'verbose_name_plural': 'Champs additionnels',
                'abstract': False,
            },
        ),
    ]
