# Generated by Django 3.2.4 on 2021-08-26 14:45

import cla_ticketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0025_dancingpartyregistrationcustomfieldvalue_eventregistrationcustomfieldvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancingpartyregistrationcustomfieldvalue',
            name='file_value',
            field=models.FileField(upload_to=cla_ticketing.models.FilePath.custom_field_file),
        ),
        migrations.AlterField(
            model_name='eventregistrationcustomfieldvalue',
            name='file_value',
            field=models.FileField(upload_to=cla_ticketing.models.FilePath.custom_field_file),
        ),
    ]
