# Generated by Django 3.2.4 on 2021-08-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0026_auto_20210826_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancingpartyregistration',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Numéro de téléphone'),
        ),
    ]
