# Generated by Django 3.2.4 on 2021-08-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0027_auto_20210826_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dancingparty',
            options={'permissions': (('dancingparty_manager', "Accès à l'interface de gestion des soirées dansantes pour lesquelles l'utilisateur est administrateur"),), 'verbose_name': 'Billetterie de soirée dansante', 'verbose_name_plural': 'Billetteries de soirée dansante'},
        ),
        migrations.AlterModelOptions(
            name='dancingpartyregistration',
            options={'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.AddField(
            model_name='dancingpartyregistration',
            name='checkin_datetime',
            field=models.DateTimeField(null=True, verbose_name="Date et heure d'entrée"),
        ),
    ]
