# Generated by Django 3.2.4 on 2021-08-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0029_dancingparty_place_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancingparty',
            name='place_index',
        ),
        migrations.AddField(
            model_name='dancingparty',
            name='allow_non_contributor_registration',
            field=models.BooleanField(default=True, verbose_name="Autoriser l'inscription des non cotisants par les cotisants"),
        ),
    ]
