# Generated by Django 3.2.4 on 2021-08-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0031_auto_20210829_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancingpartyregistrationcustomfield',
            name='delete_file_after_validation',
            field=models.BooleanField(default=False, help_text="Permet de préserver la confidentialité des données une fois qu'elles ne sont plus utiles", verbose_name='Supprimer le fichier après validation'),
        ),
        migrations.AddField(
            model_name='eventregistrationcustomfield',
            name='delete_file_after_validation',
            field=models.BooleanField(default=False, help_text="Permet de préserver la confidentialité des données une fois qu'elles ne sont plus utiles", verbose_name='Supprimer le fichier après validation'),
        ),
        migrations.AlterField(
            model_name='dancingpartyregistrationcustomfield',
            name='editable',
            field=models.BooleanField(default=False, help_text="Permet aux étudiants de modifier ce champ après avoir pris leur place, jusqu'au début de l'événement", verbose_name='Peut être modifié'),
        ),
    ]
