# Generated by Django 3.2.4 on 2021-09-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0032_auto_20210829_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancingpartyregistration',
            name='mean_of_paiement',
            field=models.CharField(blank=True, choices=[('pumpkin', 'Pumpkin'), ('money_check', 'Chèque'), ('cash', 'Liquide')], max_length=100, null=True, verbose_name='Moyen de paiement'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='mean_of_paiement',
            field=models.CharField(blank=True, choices=[('pumpkin', 'Pumpkin'), ('money_check', 'Chèque'), ('cash', 'Liquide')], max_length=100, null=True, verbose_name='Moyen de paiement'),
        ),
    ]
