# Generated by Django 3.2.4 on 2022-02-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0035_auto_20220127_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dancingparty',
            options={'permissions': (('dancingparty_manager', "Accès à l'interface de gestion des soirées dansantes pour lesquelles l'utilisateur est administrateur"), ('dancingparty_secretsauce', 'Droit particulier sur les soirées dansantes')), 'verbose_name': 'Billetterie de soirée dansante', 'verbose_name_plural': 'Billetteries de soirée dansante'},
        ),
        migrations.AddField(
            model_name='dancingpartyregistration',
            name='debug',
            field=models.BooleanField(blank=True, default=False, verbose_name='Debug'),
        ),
    ]
