# Generated by Django 3.2.4 on 2022-02-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0036_auto_20220208_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancingpartyregistration',
            name='debugged_on',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date of debugging'),
        ),
    ]
