# Generated by Django 3.2.4 on 2022-02-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0038_auto_20220223_1445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dancingpartyregistration',
            unique_together=set(),
        ),
    ]
