# Generated by Django 3.2.4 on 2022-09-10 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cla_lyfpay', '0002_alter_payment_created_by'),
        ('cla_ticketing', '0039_alter_dancingpartyregistration_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancingpartyregistration',
            name='lyfpay_payment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cla_lyfpay.payment'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='lyfpay_payment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cla_lyfpay.payment'),
        ),
    ]
