# Generated by Django 3.2.4 on 2022-09-12 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cla_lyfpay', '0001_initial'),
        ('cla_ticketing', '0039_alter_dancingpartyregistration_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancingparty',
            name='lyfpay_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cla_lyfpay.merchant', verbose_name="Compte Lyfpay d'encaissement"),
        ),
        migrations.AddField(
            model_name='dancingparty',
            name='use_integrated_payment',
            field=models.BooleanField(default=False, verbose_name='Utiliser le mode de paiement intégré plutôt que la billeterie'),
        ),
        migrations.AddField(
            model_name='dancingpartyregistration',
            name='lyfpay_payment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cla_lyfpay.payment'),
        ),
        migrations.AddField(
            model_name='event',
            name='lyfpay_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cla_lyfpay.merchant', verbose_name="Compte Lyfpay d'encaissement"),
        ),
        migrations.AddField(
            model_name='event',
            name='use_integrated_payment',
            field=models.BooleanField(default=False, verbose_name='Utiliser le mode de paiement intégré plutôt que la billeterie'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='lyfpay_payment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cla_lyfpay.payment'),
        ),
    ]
