# Generated by Django 3.2.4 on 2022-09-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_ticketing', '0040_auto_20220911_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancingparty',
            name='use_integrated_payment',
            field=models.BooleanField(default=False, verbose_name='Utiliser le mode de paiement intégré plutôt que la billeterie'),
        ),
        migrations.AddField(
            model_name='event',
            name='use_integrated_payment',
            field=models.BooleanField(default=False, verbose_name='Utiliser le mode de paiement intégré plutôt que la billeterie'),
        ),
    ]
