# Generated by Django 3.2.4 on 2022-09-10 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(choices=[('dpr', 'inscription soirée dansante')], editable=False, max_length=50)),
                ('reference', models.CharField(editable=False, max_length=250)),
                ('lyfpay_shop_reference', models.CharField(editable=False, max_length=80, unique=True)),
                ('lyfpay_shop_order_reference', models.CharField(editable=False, max_length=80)),
                ('lyfpay_id', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('lyfpay_amount', models.PositiveSmallIntegerField(editable=False)),
                ('lyfpay_status', models.CharField(choices=[('WAITING', 'en attente'), ('VALIDATED', 'validé'), ('REFUSED', 'refusé'), ('FAILED', 'échoué')], default='WAITING', editable=False, max_length=20)),
                ('lyfpay_updated_at', models.DateTimeField(editable=False, null=True)),
                ('notes', models.TextField(blank=True, default='', max_length=1000)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cla_lyfpay.wallet')),
            ],
        ),
    ]
