# Generated by Django 3.2.4 on 2022-01-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-starts_on',), 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
    ]
