# Generated by Django 3.2.4 on 2022-01-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_event', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplace',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
    ]
