# Generated by Django 3.2.4 on 2022-01-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_event', '0005_event_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='member_display',
            field=models.BooleanField(default=True, verbose_name="L'événement apparait sur le planning des cotisants"),
        ),
        migrations.AlterField(
            model_name='event',
            name='admin_display',
            field=models.BooleanField(default=False, verbose_name="L'événement apparait sur le planning de l'administration"),
        ),
    ]
