# Generated by Django 3.2.4 on 2022-05-14 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cla_event', '0006_auto_20220122_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Annulé par'),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled_hide',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Annulé le'),
        ),
    ]
