# Generated by Django 3.1.3 on 2021-03-21 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cla_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='activated_on',
            field=models.DateTimeField(null=True, verbose_name="Date d'activation du compte"),
        ),
        migrations.AddField(
            model_name='userinfos',
            name='birthdate',
            field=models.DateField(default=None, verbose_name='Date de naissance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfos',
            name='email_school',
            field=models.EmailField(default='', max_length=254, verbose_name="Adresse mail de l'école"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfos',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userinfos',
            name='valid_until',
            field=models.DateTimeField(null=True, verbose_name="Compte valide jusqu'au"),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='cursus',
            field=models.CharField(choices=[('G1', 'G1'), ('G1-DD-EDHEC', 'G1 en double diplôme avec EDHEC'), ('G1-DD-INTERNATIONAL', 'G1 en double diplôme international'), ("G1'", "G1'"), ("G1'-DD-EDHEC", "G1' en double diplôme EDHEC"), ("G1'-DD-INTERNATIONAL", "G1' en double diplôme international"), ('G2', 'G2'), ('G2-DD-EDHEC', "G2 en double diplôme avec l'EDHEC"), ('G2-DD-INTERNATIONAL', 'G2 en double diplôme international'), ('G2-CESURE-FEV', 'G2 en césure février/février'), ('G2-CESURE-SEPT', 'G2 en année sabatique'), ("G2'", "G2'"), ("G2'-DD-EDHEC", "G2' en double diplôme avec l'EDHEC"), ("G2'-DD-INTERNATIONAL", "G2' en double diplôme international"), ("G2'-CESURE-FEV", 'G2 en césure février/février'), ("G2'-CESURE-SEPT", 'G2 en année sabatique'), ('G3', 'G3'), ('G3-GEC', 'G3 en mobilité intercentrale'), ('G3-DD-EDHEC', "Double diplôme avec l'EDHEC"), ('DD-INTERNATIONAL', 'Double diplôme internationnal'), ('DD-FRANCE', 'Double diplôme en France'), ('G3-DIPLOME-DD-EDHEC', 'Diplomé'), ('G3-DIPLOME-DD-INTERNATIONAL', 'Diplomé'), ('G3-DIPLOME', 'Diplomé'), ('IE1', 'Ie1'), ("IE1'", 'Ie1P'), ('IE2', 'Ie2'), ("IE2'", 'Ie2P'), ('IE3', 'Ie3'), ('IE3P', 'Ie3P'), ('IE4', 'Ie4'), ("IE4'", 'Ie4P'), ('IE5', 'Ie5'), ("IE5'", 'Ie5P'), ('IE5-DIPLOME', 'Ie5 Diplome'), ('Autre', 'Autre cursus')], max_length=100, null=True, verbose_name='Cursus'),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='promo',
            field=models.PositiveIntegerField(verbose_name="Promotion (lors de l'arrivée à Centrale)"),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('paid_on', models.DateField()),
                ('paid_by', models.CharField(choices=[('Pumpkin', 'pumpkin'), ('Chèque', 'check'), ('Liquide', 'cash'), ('Virement', 'transfer'), ('Carte bancaire', 'card')], max_length=100)),
                ('refunded', models.PositiveIntegerField(blank=True, null=True)),
                ('refunded_on', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
