# Generated by Django 3.1.3 on 2021-03-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0002_auto_20210321_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='refunded_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Montant remboursé'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Montant de la cotisation'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='paid_by',
            field=models.CharField(choices=[('Pumpkin', 'pumpkin'), ('Chèque', 'check'), ('Liquide', 'cash'), ('Virement', 'transfer'), ('Carte bancaire', 'card')], max_length=100, verbose_name='Moyen de paiement'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='paid_on',
            field=models.DateField(verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='refunded',
            field=models.BooleanField(blank=True, default=False, verbose_name='La cotisation a été remboursée'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='refunded_on',
            field=models.DateField(blank=True, null=True, verbose_name='Date du remboursement'),
        ),
    ]
