# Generated by Django 3.1.3 on 2021-04-16 14:08

import cla_auth.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0003_auto_20210321_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='account_type',
            field=models.CharField(choices=[('student', 'Étudiant'), ('school', "Personnel de l'école"), ('admin', 'Compte administrateur'), ('other', 'Autre')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfos',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=90, size=[500, 500], upload_to=cla_auth.models.FilePath.picture, verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='cursus',
            field=models.CharField(choices=[('G1', 'G1'), ('G1-DD-EDHEC', 'G1 en double diplôme avec EDHEC'), ('G1-DD-INTERNATIONAL', 'G1 en double diplôme international'), ("G1'", "G1'"), ("G1'-DD-EDHEC", "G1' en double diplôme EDHEC"), ("G1'-DD-INTERNATIONAL", "G1' en double diplôme international"), ('G2', 'G2'), ('G2-DD-EDHEC', "G2 en double diplôme avec l'EDHEC"), ('G2-DD-INTERNATIONAL', 'G2 en double diplôme international'), ('G2-CESURE-FEV', 'G2 en césure février/février'), ('G2-CESURE-SEPT', 'G2 en année sabatique'), ("G2'", "G2'"), ("G2'-DD-EDHEC", "G2' en double diplôme avec l'EDHEC"), ("G2'-DD-INTERNATIONAL", "G2' en double diplôme international"), ("G2'-CESURE-FEV", 'G2 en césure février/février'), ("G2'-CESURE-SEPT", 'G2 en année sabatique'), ('G3', 'G3'), ('G3-GEC', 'G3 en mobilité intercentrale'), ('G3-DD-EDHEC', "Double diplôme avec l'EDHEC"), ('DD-INTERNATIONAL', 'Double diplôme internationnal'), ('DD-FRANCE', 'Double diplôme en France'), ('G3-DIPLOME-DD-EDHEC', 'Diplomé'), ('G3-DIPLOME-DD-INTERNATIONAL', 'Diplomé'), ('G3-DIPLOME', 'Diplomé'), ('IE1', 'IE1'), ('IE1P', "IE1'"), ('IE2', 'IE2'), ('IE2P', "IE2'"), ('IE3', 'IE3'), ('IE3P', "IE3'"), ('IE4', 'IE4'), ('IE4P', "IE4'"), ('IE5', 'IE5'), ('IE5P', "IE5'"), ('IE5-DIPLOME', 'Ie5 Diplome'), ('Autre', 'Autre cursus')], max_length=100, null=True, verbose_name='Cursus'),
        ),
    ]
