# Generated by Django 3.1.3 on 2021-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0004_auto_20210416_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfos',
            options={'verbose_name': 'Information'},
        ),
        migrations.AlterModelOptions(
            name='usermembership',
            options={'verbose_name': 'Cotisation'},
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='account_type',
            field=models.CharField(choices=[('student', 'Étudiant'), ('school', "Personnel de l'école"), ('other', 'Autre')], default='student', max_length=10, verbose_name='Type de compte'),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone'),
        ),
    ]
