# Generated by Django 3.1.3 on 2021-04-16 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cla_auth', '0005_auto_20210416_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True, verbose_name='Identifiant du service')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('domain', models.CharField(max_length=250, verbose_name='Nom de domaine du service')),
                ('endpoint', models.CharField(max_length=250, verbose_name='Endpoint du service')),
                ('validation_required', models.BooleanField(default=True, verbose_name='La validation est requise pour se connecter')),
                ('authorization_required', models.BooleanField(default=True, verbose_name="L'utilisateur doit approuvé le partage d'information lors de la première utilisation")),
                ('cursus', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G1', 'G1'), ('G1-DD-EDHEC', 'G1 en double diplôme avec EDHEC'), ('G1-DD-INTERNATIONAL', 'G1 en double diplôme international'), ("G1'", "G1'"), ("G1'-DD-EDHEC", "G1' en double diplôme EDHEC"), ("G1'-DD-INTERNATIONAL", "G1' en double diplôme international"), ('G2', 'G2'), ('G2-DD-EDHEC', "G2 en double diplôme avec l'EDHEC"), ('G2-DD-INTERNATIONAL', 'G2 en double diplôme international'), ('G2-CESURE-FEV', 'G2 en césure février/février'), ('G2-CESURE-SEPT', 'G2 en année sabatique'), ("G2'", "G2'"), ("G2'-DD-EDHEC", "G2' en double diplôme avec l'EDHEC"), ("G2'-DD-INTERNATIONAL", "G2' en double diplôme international"), ("G2'-CESURE-FEV", 'G2 en césure février/février'), ("G2'-CESURE-SEPT", 'G2 en année sabatique'), ('G3', 'G3'), ('G3-GEC', 'G3 en mobilité intercentrale'), ('G3-DD-EDHEC', "Double diplôme avec l'EDHEC"), ('DD-INTERNATIONAL', 'Double diplôme internationnal'), ('DD-FRANCE', 'Double diplôme en France'), ('G3-DIPLOME-DD-EDHEC', 'Diplomé'), ('G3-DIPLOME-DD-INTERNATIONAL', 'Diplomé'), ('G3-DIPLOME', 'Diplomé'), ('IE1', 'IE1'), ('IE1P', "IE1'"), ('IE2', 'IE2'), ('IE2P', "IE2'"), ('IE3', 'IE3'), ('IE3P', "IE3'"), ('IE4', 'IE4'), ('IE4P', "IE4'"), ('IE5', 'IE5'), ('IE5P', "IE5'"), ('IE5-DIPLOME', 'Ie5 Diplome'), ('Autre', 'Autre cursus')], max_length=376, verbose_name='Cursus autorisés à se connecter')),
                ('auto_login', models.BooleanField(default=True, verbose_name='Connexion automatique')),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=250)),
                ('used', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cla_auth.service', to_field='identifier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cla_auth.service', to_field='identifier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
