# Generated by Django 3.1.3 on 2021-04-16 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cla_auth', '0008_auto_20210416_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='authorization_required',
            field=models.BooleanField(default=True, verbose_name="L'utilisateur doit approuver le partage d'informations lors de la première utilisation"),
        ),
        migrations.AlterField(
            model_name='service',
            name='colleges',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('g1', 'G1'), ('g2', 'G2'), ('g3', 'G3'), ('alumni-centrale', 'Diplomé de Centrale'), ('ie1/ie2', 'IE1/IE2'), ('ie3', 'IE3'), ('ie4', 'IE4'), ('ie5', 'IE5'), ('alumni-iteem', "Diplomé de l'ITEEM")], max_length=57, verbose_name='Collèges autorisés à se connecter'),
        ),
        migrations.CreateModel(
            name='ValidationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_school', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('sent_on', models.DateTimeField(null=True)),
                ('code', models.IntegerField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('sent_on', models.DateTimeField(null=True)),
                ('token', models.CharField(max_length=250)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_school', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('sent_on', models.DateTimeField(null=True)),
                ('token', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
