# Generated by Django 3.1.3 on 2021-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0009_auto_20210416_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetrequest',
            options={'ordering': ('created_on',)},
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
    ]
