# Generated by Django 3.1.3 on 2021-04-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0010_auto_20210417_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationRequest',
        ),
    ]
