# Generated by Django 3.2 on 2021-04-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0012_auto_20210417_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfos',
            options={'permissions': (('manage_user_activation', "Accès au processus d'activation des comptes"), ('manage_user_validation', 'Accès au processus de validation des comptes'), ('manage_user_password', 'Accès au processus de réinitialisation des mots de passes')), 'verbose_name': 'Information'},
        ),
    ]
