# Generated by Django 3.2 on 2021-04-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0013_alter_userinfos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='paid_by',
            field=models.CharField(choices=[('pumpkin', 'Pumpkin'), ('check', 'Chèque'), ('cash', 'Liquide'), ('transfer', 'Virement'), ('card', 'Carte bancaire')], max_length=100, verbose_name='Moyen de paiement'),
        ),
    ]
