# Generated by Django 3.2 on 2021-04-22 09:47

import cla_web.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0015_auto_20210418_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrequest',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validationrequest',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='validationrequest',
            name='code',
            field=models.IntegerField(default=cla_web.utils.random_six_digits),
        ),
    ]
