# Generated by Django 3.2 on 2021-04-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0016_auto_20210422_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
