# Generated by Django 3.2 on 2021-06-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0019_remove_serviceticket_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfos',
            options={'permissions': (('manage_user_activation', "Accès au processus d'activation des comptes"), ('manage_user_validation', 'Accès au processus de validation des comptes'), ('manage_user_password', 'Accès au processus de réinitialisation des mots de passes'), ('autocomplete_user', "Accès à la fonctionnalité d'autocomplétion sur les champs utilisateur")), 'verbose_name': 'Information'},
        ),
    ]
