# Generated by Django 3.2.4 on 2021-06-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0020_alter_userinfos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='amount',
            field=models.PositiveIntegerField(blank=True, verbose_name='Montant de la cotisation'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='paid_on',
            field=models.DateField(null=True, verbose_name='Date de paiement'),
        ),
    ]
