# Generated by Django 3.2.4 on 2021-08-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0022_auto_20210606_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='original_school',
            field=models.CharField(max_length=255, null=True, verbose_name="École/université d'origine"),
        ),
    ]
