# Generated by Django 3.2.4 on 2021-09-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0024_alter_userinfos_cursus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfos',
            options={'permissions': (('manage_user_activation', "Accès au processus d'activation des comptes"), ('manage_user_validation', 'Accès au processus de validation des comptes'), ('manage_user_password', 'Accès au processus de réinitialisation des mots de passes'), ('autocomplete_user', "Accès à la fonctionnalité d'autocomplétion sur les champs utilisateur"), ('upload_user_picture', 'Accès à la fonctionnalité de mise en ligne des photos utilisateurs')), 'verbose_name': 'Information'},
        ),
    ]
