# Generated by Django 3.2.4 on 2021-09-03 09:47

import cla_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0027_auto_20210903_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=cla_auth.models.FilePath.picture, verbose_name='Photo de profil'),
        ),
    ]
