# Generated by Django 3.2.4 on 2021-12-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0030_auto_20211028_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='cursus',
            field=models.CharField(choices=[('G1', 'G1'), ('G1-DD-EDHEC', 'G1 en double diplôme avec EDHEC'), ('G1-DD-INTERNATIONAL', 'G1 en double diplôme international'), ("G1'", "G1'"), ("G1'-DD-EDHEC", "G1' en double diplôme EDHEC"), ("G1'-DD-INTERNATIONAL", "G1' en double diplôme international"), ('G2', 'G2'), ('G2-DD-EDHEC', "G2 en double diplôme avec l'EDHEC"), ('G2-DD-INTERNATIONAL', 'G2 en double diplôme international'), ('G2-CESURE-FEV', 'G2 en césure février/février'), ('G2-CESURE-SEPT', 'G2 en année sabatique'), ("G2'", "G2'"), ("G2'-DD-EDHEC", "G2' en double diplôme avec l'EDHEC"), ("G2'-DD-INTERNATIONAL", "G2' en double diplôme international"), ("G2'-CESURE-FEV", 'G2 en césure février/février'), ("G2'-CESURE-SEPT", 'G2 en année sabatique'), ('G3', 'G3'), ('G3-GEC', 'G3 en mobilité intercentrale'), ('G3-DD-EDHEC', "Double diplôme avec l'EDHEC"), ('G3-DD-SCIENCESPO', 'Double diplôme avec Sciences Po'), ('G3-DD-INTERNATIONAL', 'Double diplôme internationnal'), ('G3-DD-FRANCE', 'Double diplôme en France'), ('G3-DIPLOME-DD-EDHEC', 'Diplomé DD EDHEC'), ('G3-DIPLOME-DD-INTERNATIONAL', 'Diplomé DD Internationnal'), ('G3-DIPLOME', 'Diplomé de Centrale'), ('IE1', 'IE1'), ('IE1P', "IE1'"), ('IE2', 'IE2'), ('IE2P', "IE2'"), ('IE3', 'IE3'), ('IE3P', "IE3'"), ('IE4', 'IE4'), ('IE4P', "IE4'"), ('IE5', 'IE5'), ('IE5P', "IE5'"), ('IE5-DIPLOME', 'Diplomé de l\\ITEEM'), ('CENTRALE-PHD', 'Doctorant'), ('Autre', 'Autre cursus')], max_length=100, null=True, verbose_name='Cursus'),
        ),
    ]
