# Generated by Django 3.2.4 on 2022-09-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0033_alter_service_colleges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('lyfpay', 'Lyf pay'), ('lydia', 'Lydia'), ('pumpkin', 'Pumpkin'), ('check', 'Chèque'), ('cash', 'Liquide'), ('transfer', 'Virement'), ('card', 'Carte bancaire')], max_length=100, verbose_name='Moyen de paiement'),
        ),
    ]
