# Generated by Django 3.2.4 on 2025-08-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0034_alter_usermembership_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='alumni_pack',
            field=models.BooleanField(blank=True, null=True, verbose_name='A cotisé avec le pack alumni'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='payment_installments',
            field=models.PositiveSmallIntegerField(
                choices=[(1, "En 1 fois"), (2, "En 2 fois"), (3, "En 3 fois")],
                blank=True,
                null=True,
                verbose_name='Paiement en X fois'
            ),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='payment_months',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Étalé sur 1 mois"),
                    (2, "Étalé sur 2 mois"),
                    (3, "Étalé sur 3 mois"),
                    (4, "Étalé sur 4 mois"),
                    (5, "Étalé sur 5 mois"),
                    (6, "Étalé sur 6 mois"),
                ],
                blank=True,
                null=True,
                verbose_name='Étalé sur X mois'
            ),
        ),
    ]
