# Generated by Django 3.2.4 on 2025-08-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_auth', '0036_migrate_paiement_and_alumni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='paiement_method',
        ),
    ]
