# Generated by Django 3.2.4 on 2021-08-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Site partenaire', 'verbose_name_plural': 'Sites partenaires'},
        ),
    ]
