# Generated by Django 3.2.4 on 2021-08-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_member', '0002_alter_website_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='display',
            field=models.BooleanField(default=True, verbose_name="Afficher le site dans l'espace adhérent"),
        ),
    ]
