# Generated by Django 3.2.4 on 2021-08-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla_member', '0005_alter_website_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
    ]
